# Generated by Django 2.2.13 on 2021-03-01 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Kraj zakwaterowania')),
                ('equivalent', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='DailyTransport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_of_moving', models.CharField(choices=[('B', 'rower'), ('T', 'tramwaj'), ('M', 'metro'), ('B', 'autobus'), ('DE', 'somochód disel'), ('HE', 'samochód hybrydowy'), ('EC', 'samochód elektryczny')], max_length=120, verbose_name='Środek transportu')),
                ('distance_in_km', models.IntegerField(verbose_name='Pokonany dystans w km')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_food', models.CharField(max_length=120)),
                ('equivalent', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('household', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], verbose_name='Liczba osób w gospodarstwie domowym')),
                ('type_of_heating', models.CharField(choices=[('E', 'energia elektryczna [kWh]'), ('G', 'gaz ziemny [kWh]'), ('C', 'węgiel [t]'), ('W', 'drewno opałowe [t]'), ('L', 'LPG [l]'), ('O', 'olej opałowy [l]')], max_length=120, verbose_name='Forma ogrzewania')),
                ('amount', models.IntegerField(verbose_name='Wartość zużyta')),
            ],
        ),
        migrations.CreateModel(
            name='InformationPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode_of_transport', models.CharField(choices=[('T', 'pociąg'), ('B', 'autokar'), ('DE', 'somochód disel'), ('HE', 'samochód hybrydowy'), ('EC', 'samochód elektryczny'), ('DF', 'lot krajowy'), ('SF', 'lot krótkodystansowy < 3700 km'), ('LF', 'lot długodystansowy > 3700 km')], max_length=120, verbose_name='Środek transportu')),
                ('length_of_distance', models.IntegerField(verbose_name='Pokonany dystans w km')),
                ('number_of_night', models.IntegerField(verbose_name='Liczba nocy')),
            ],
        ),
    ]
