# Generated by Django 3.0.2 on 2020-01-29 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTransport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_of_moving', models.CharField(choices=[(1, 'rower'), (2, 'tramwaj'), (3, 'metro'), (4, 'autobus'), (5, 'somochód disel'), (6, 'samochód hybrydowy'), (7, 'samochód elektryczny')], max_length=120, verbose_name='Forma przemiszczania się')),
                ('distance_in_km', models.IntegerField(verbose_name='Pokonany dystans w km')),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_house', models.TextField()),
                ('household', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], verbose_name='Liczba osób w gospodarstwie domowym')),
                ('type_of_heating', models.CharField(choices=[(1, 'energia elektryczna [kWh]'), (2, 'gaz ziemny [kWh]'), (3, 'węgiel [t]'), (4, 'drewno opałowe i odpady pochodzenia drzewnego [t]'), (5, 'LPG [l]'), (6, 'olej opałowy [l]')], max_length=120, verbose_name='Forma ogrzewania')),
                ('amount', models.IntegerField(verbose_name='Wartość zurzyta')),
            ],
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_travel', models.TextField()),
                ('mode_of_transport', models.CharField(choices=[(1, 'pociąg'), (2, 'autokar'), (3, 'somochód disel'), (4, 'samochód hybrydowy'), (5, 'samochód elektryczny'), (6, 'lot krajowy'), (7, 'lot krótkodystansowy < 3700 km'), (8, 'lot długodystansowy > 3700 km')], max_length=120, verbose_name='Środek transportu')),
                ('length_of_distance', models.IntegerField(verbose_name='Pokonany dystans [km]')),
                ('country_of_accommodation', models.CharField(max_length=60, verbose_name='Kraj zakwaterowania')),
                ('number_of_night', models.IntegerField(verbose_name='Liczba dni przebywania w miejscu zakwaterowanym')),
            ],
        ),
    ]
