# Generated by Django 3.0.2 on 2020-01-29 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbon_footprint_calculator', '0002_mainpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailytransport',
            name='form_of_moving',
            field=models.IntegerField(choices=[(1, 'rower'), (2, 'tramwaj'), (3, 'metro'), (4, 'autobus'), (5, 'somochód disel'), (6, 'samochód hybrydowy'), (7, 'samochód elektryczny')], max_length=120, verbose_name='Forma przemiszczania się'),
        ),
    ]
