# Generated by Django 3.0.2 on 2020-01-30 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbon_footprint_calculator', '0005_auto_20200129_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='type_of_heating',
            field=models.CharField(choices=[(1, 'energia elektryczna [kWh]'), (2, 'gaz ziemny [kWh]'), (3, 'węgiel [t]'), (4, 'drewno opałowe [t]'), (5, 'LPG [l]'), (6, 'olej opałowy [l]')], max_length=120, verbose_name='Forma ogrzewania'),
        ),
    ]
