# Generated by Django 3.0.2 on 2020-01-30 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbon_footprint_calculator', '0006_auto_20200130_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailytransport',
            name='form_of_moving',
            field=models.CharField(choices=[(1, 'rower'), (2, 'tramwaj'), (3, 'metro'), (4, 'autobus'), (5, 'somochód disel'), (6, 'samochód hybrydowy'), (7, 'samochód elektryczny')], max_length=120, verbose_name='Środek transportu'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='length_of_distance',
            field=models.IntegerField(verbose_name='Pokonany dystans w km'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='number_of_night',
            field=models.IntegerField(verbose_name='Liczba nocy'),
        ),
    ]
