# Generated by Django 3.0.2 on 2020-01-30 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carbon_footprint_calculator', '0007_auto_20200130_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='text_house',
        ),
        migrations.RemoveField(
            model_name='travel',
            name='text_travel',
        ),
    ]
