# Generated by Django 3.0.2 on 2020-01-30 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbon_footprint_calculator', '0009_house_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='type_of_heating',
            field=models.CharField(choices=[('energia elektryczna [kWh]', 'energia elektryczna [kWh]'), ('gaz ziemny [kWh]', 'gaz ziemny [kWh]'), (3, 'węgiel [t]'), (4, 'drewno opałowe [t]'), (5, 'LPG [l]'), (6, 'olej opałowy [l]')], max_length=120, verbose_name='Forma ogrzewania'),
        ),
    ]
