# Generated by Django 3.0.2 on 2020-01-30 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbon_footprint_calculator', '0010_auto_20200130_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailytransport',
            name='form_of_moving',
            field=models.CharField(choices=[('rower', 'rower'), ('tramwaj', 'tramwaj'), ('metro', 'metro'), ('autobus', 'autobus'), ('somochód disel', 'somochód disel'), ('samochód hybrydowy', 'samochód hybrydowy'), ('samochód elektryczny', 'samochód elektryczny')], max_length=120, verbose_name='Środek transportu'),
        ),
        migrations.AlterField(
            model_name='house',
            name='type_of_heating',
            field=models.CharField(choices=[('energia elektryczna [kWh]', 'energia elektryczna [kWh]'), ('gaz ziemny [kWh]', 'gaz ziemny [kWh]'), ('węgiel [t]', 'węgiel [t]'), ('drewno opałowe [t]', 'drewno opałowe [t]'), ('LPG [l]', 'LPG [l]'), ('olej opałowy [l]', 'olej opałowy [l]')], max_length=120, verbose_name='Forma ogrzewania'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='mode_of_transport',
            field=models.CharField(choices=[('pociąg', 'pociąg'), ('autokar', 'autokar'), ('somochód disel', 'somochód disel'), ('samochód hybrydowy', 'samochód hybrydowy'), ('samochód elektryczny', 'samochód elektryczny'), ('lot krajowy', 'lot krajowy'), ('lot krótkodystansowy < 3700 km', 'lot krótkodystansowy < 3700 km'), ('lot długodystansowy > 3700 km', 'lot długodystansowy > 3700 km')], max_length=120, verbose_name='Środek transportu'),
        ),
    ]
