# Generated by Django 3.0.2 on 2020-01-30 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carbon_footprint_calculator', '0012_remove_house_result'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MainPage',
            new_name='InformationPage',
        ),
    ]
