# Generated by Django 3.0.2 on 2020-01-30 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbon_footprint_calculator', '0013_auto_20200130_1451'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travel',
            old_name='country_of_accommodation',
            new_name='country',
        ),
        migrations.AddField(
            model_name='travel',
            name='equivalent',
            field=models.FloatField(default=0),
        ),
    ]
