# Generated by Django 3.0.2 on 2020-01-30 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbon_footprint_calculator', '0014_auto_20200130_2017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Kraj zakwaterowania')),
                ('equivalent', models.FloatField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='travel',
            name='country',
        ),
        migrations.RemoveField(
            model_name='travel',
            name='equivalent',
        ),
    ]
