# Generated by Django 3.0.2 on 2020-01-30 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbon_footprint_calculator', '0015_auto_20200130_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='equivalent',
            field=models.FloatField(),
        ),
    ]
